### PR TITLE
fix: Auto doc signal list

### LINKED ISSUE #426: No signallist export with new NWHEI SCD
Steps to reproduce:
1. Create a signallist with the new NHWEI SCD
2. Select all checkboxes
3. Export the pdf and xls

Current
The xls shows no signallist details (only header) 

Expected:
The xls shows all selected signallist details

Hints, see Rezas mail:
Position of LN0 and the datasets below it are different to the old scd:

LN0 is located in 'SE_GSE_Example*.scd' under a specific LDevice (in this case: <LDevice inst=“SWEQ”>). It seems that each LDevice has its own LN0.

but in the file '2025-01-29-NWH*.scd', all datasets and report/GSEControls are under <LDevice inst=“LD0”> <LN0 lnType=“LLN0$oscd$_72a1a36f04dd9362” inst=“” lnClass=“LLN0”>)

In the file “2025-01-29-NWH*.scd” there is no description (desc=) for the signal name, which is additional (optional) information in “SE_GSE_Example*.scd”.

### PR DESCRIPTION
**Pull request by clepski**
# 🗒 Description

Closes #426, #474

Fix auto doc signallist: List is based on subscribers (ExtRef elements).

~~To quickly deploy and test the feature adjusting the tests has been extracted to #474~~

## 📋 Checklist

You may remove tasks that do not make sense in this PR.

- [x] GitHub **labels** are assigned
- [x] Git Ticket / issue  is linked with PR
- [x] Designated PR Reviewers are set
- [x] Tested by another developer
- [x] Changelog updated
- [x] All comments in the PR are resolved / answered

### CODE REVIEW

File: packages/plugins/auto-doc/src/components/elements/signal-list-element/signal-list-element.svelte [hunk 1]
```diff
@@ -113,34 +113,27 @@
...
 			}
 		}
 	
-		const { messagePublishers } =
-			signallistStore.getPublishingLogicalDevices(publisherFilter)
-		const { matchedRows } = signallistStore.getSubscribingLogicalDevices(
-			messagePublishers,
-			subscriberFilter
-		)
+		const { pdfRows, invaliditiesReports } = signallistStore.getPublishingLogicalDevices(publisherFilter, subscriberFilter);
```
Comment (michelguerin) [inline packages/plugins/auto-doc/src/components/elements/signal-list-element/signal-list-element.svelte:127]: I'm a bit confused here as pdfRows coming from getPublishing is replacing matchedRows that comes from a getSubscribing function. Is there a naming issue here ?

File: packages/plugins/auto-doc/src/utils/pdfGenerator.ts [hunk 2]
```diff
@@ -2,8 +2,8 @@ import jsPDF from 'jspdf';
 import autoTable from 'jspdf-autotable';
 import zipcelx from 'zipcelx';
 import type {ElementType} from "@/components/elements/types.elements"
-import {docTemplatesStore, placeholderStore} from '@/stores'
-import type {Columns, SignalType} from '@/stores'
+import {docTemplatesStore, placeholderStore} from '../stores'
+import type {Columns, SignalType} from '../stores'
```
Comment (michelguerin) [inline packages/plugins/auto-doc/src/utils/pdfGenerator.ts:6]: Is there a reason why you changed these alias ?

File: packages/plugins/auto-doc/src/stores/signallist.store.ts [hunk 3]
```diff
@@ -20,330 +20,445 @@ const { xmlDocument } = pluginStore
 const pdfRowValues = writable<PdfRowStructure[]>([])
 
 
-//==== PUBLIC ACTIONS
-function getSignallist() {
-    const xmlDoc = get(xmlDocument);
-    if (!xmlDoc) {
-        throw new Error("XML Document is not defined");
-    }
+//==== new attempt, i cant take all this terrible code anymore
```
Comment (michelguerin) [inline packages/plugins/auto-doc/src/stores/signallist.store.ts:23]: I get the idea, but please don't push this kind of comments

Comment (clepski) [reply packages/plugins/auto-doc/src/stores/signallist.store.ts:23]: Yea sorry, that was more for me internally, I will remove it

File: packages/plugins/auto-doc/src/utils/pdfGenerator.ts (hunk 2 above)
Comment (clepski) [reply packages/plugins/auto-doc/src/utils/pdfGenerator.ts:6]: The Aliases broke the tests, I haven't figured out why. I did ask about it in Teams

File: packages/plugins/auto-doc/src/components/elements/signal-list-element/signal-list-element.svelte (hunk 1 above)
Comment (clepski) [reply packages/plugins/auto-doc/src/components/elements/signal-list-element/signal-list-element.svelte:127]: So before it would first create all rows (1 row = 1 publisher) without subscribers and then add the subscribers, but I have changed it in a way that first all data is collected and then you generate the rows from the data.

It is still 1 row = 1 publisher and subscribers are added as a column in that row, but I wanted to separate collecting data and transforming data to a pdf row.
