### PR TITLE
Fix/UI svelte dark theme leak

### LINKED ISSUE #299: Font color - Communication Explorer, Network Explorer or Documentation Plugin
Steps to reproduce:

1. Open OpenSCD and load SCD
2. Open Communication Explorer, Network Explorer or Documentation Plugin

Current:
- font color for some elements is white

Expected:
- font color should be displayed like before (e.g. gray)

### PR DESCRIPTION
**Pull request by michelguerin**
# 🗒 Description

When loading the type-designer plugin, there was a dark theme issue for some plugin (communication explorer and auto-doc for example).
The issue came from the  ui-svelte package and the sonner component. It was imported the mode-watcher (an utility to watch the css `prefers-color-scheme`class), which automatically added the class to the document (which is not used otherwise by the instance for now), based on system preference : often dark mode.

This dependency was removed.

## 🔦 Related

Closes #299

### CODE REVIEW

File: packages/uilib/src/lib/components/diagram/ied-element/ied-element.svelte [hunk 1]
```diff
@@ -37,7 +38,6 @@ export let testid = ''
 
 		/* TODO: extract colors */
 		background: var(--color-white);
-		color: var(--color-black);
```
Comment (trusz) [inline packages/uilib/src/lib/components/diagram/ied-element/ied-element.svelte:40]: is this the fix?

Comment (michelguerin) [reply packages/uilib/src/lib/components/diagram/ied-element/ied-element.svelte:40]: Nop the fix is present in 3cd148c 
This is part of a commit I **reverted** (initial fix attempt, only scoped on the communcation explorer plugin) f6ba09a

**Review by AbdelazizTina-dev — APPROVED** [review]
