### PR TITLE
Fix(dist): hide apply button

### LINKED ISSUE #652: Apply BayType Button remove when auto matched

### PR DESCRIPTION
**Pull request by tmenzel27**
# 🗒 Description

Goal to refactor the complex if else, but I do not feel like I suceeded :D 
- PendingBayType when auto works -> shows BayTypeDetails
- if countmismatch -> just show error
- if ambigious -> show Equipment matching
- pressing apply hides view

## 📷 Demo screen recording or Screenshots

- [x] Not applicable

## 📋 Checklist

You may remove tasks that do not make sense in this PR.

- [x] Ticket-ACs are checked and met
- [x] GitHub **labels** are assigned
- [x] Git Ticket / issue  is linked with PR
- [ ] Designated PR Reviewers are set
- [ ] Tested by another developer
- [ ] Changelog updated
- [ ] Documentation updated (check [Documentation guidelines](../doc/guidelines/doc_guidelines.md) for further reading )
- [ ] All comments in the PR are resolved / answered

## 🔦 Useful commits

You can add specific commits which are worth taking a look into

## ❌ Link issue(s) to close - [hint](https://docs.github.com/en/issues/tracking-your-work-with-issues/using-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)

closes #652

### CODE REVIEW

File: packages/plugins/type-distributor/src/ui/components/views/type-distributor-view.svelte [hunk 1]
```diff
@@ -37,16 +44,41 @@ const sIedItems = $derived.by(() => {
...
 
+const shouldShowBayTypeDetails = $derived.by(() => {
+	if (!bayTypeWithTemplates) return false
+
+	const validation = equipmentMatchingStore.validationResult
+
+	if (
+		validation &&
+		!validation.isValid &&
+		!validation.requiresManualMatching
```
Comment (tmenzel27) [inline packages/plugins/type-distributor/src/ui/components/views/type-distributor-view.svelte]: just isValid should be enough

**Review by maxschmalenbach — APPROVED** [review]
